AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB

Resources:
  DDBWorkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: canvas-nft-work
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: Status
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: Status-Index
          KeySchema:
            - AttributeName: Status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  DDBThumbnailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: canvas-nft-thumbnail
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: WorkID
          AttributeType: S
        - AttributeName: Order
          AttributeType: N
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: ID-Order-Index
          KeySchema:
            - AttributeName: ID
              KeyType: HASH
            - AttributeName: Order
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: WorkID-Order-Index
          KeySchema:
            - AttributeName: WorkID
              KeyType: HASH
            - AttributeName: Order
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  DDBUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: canvas-nft-user
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: WalletAddress
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: WalletAddress-Index
          KeySchema:
            - AttributeName: WalletAddress
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  DDBAssetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: canvas-nft-asset
      AttributeDefinitions:
        - AttributeName: WorkID
          AttributeType: S
      KeySchema:
        - AttributeName: WorkID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1