version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "canvas-store-server"
s3_bucket = "canvas-store-artifact"
s3_prefix = "canvas-store"
region = "ap-northeast-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"